/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cities_inc;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Patrik
 */
public class AdminScreen extends javax.swing.JFrame {//aqui apareceran los datos de todos los usuarios

    /**
     * Creates new form AdminScreen
     */
    public AdminScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnCrearUsuario = new javax.swing.JButton();
        BtnBorrarUsuario = new javax.swing.JButton();
        BtnCambiarPassword = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCSP = new javax.swing.JTextField();
        jPasswordFieldContrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        BtnCrearUsuario.setText("Crear Usuario");
        BtnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearUsuarioActionPerformed(evt);
            }
        });

        BtnBorrarUsuario.setText("Borrar usuario");
        BtnBorrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarUsuarioActionPerformed(evt);
            }
        });

        BtnCambiarPassword.setText("Restablecer contraseña");
        BtnCambiarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCambiarPasswordActionPerformed(evt);
            }
        });

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Contraseña:");

        jLabel3.setText("CSP:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldCSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jPasswordFieldContrasena))))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnSalir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnCambiarPassword)
                            .addComponent(BtnCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnBorrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jPasswordFieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldCSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(BtnCrearUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBorrarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCambiarPassword)
                        .addGap(40, 40, 40)
                        .addComponent(BtnSalir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearUsuarioActionPerformed
        // TODO add your handling code here:
        //codigo query para crear un usuario desde la pantalla de administrador
        String sql;
        if (jTextFieldNombre.getText().isEmpty() || jPasswordFieldContrasena.getPassword().length == 0 || jTextFieldCSP.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "¡Introduzca todos los datos!");
        } else {
            String nombreUsuario = jTextFieldNombre.getText();
            String password = String.valueOf(jPasswordFieldContrasena.getPassword());
            int CSP = Integer.valueOf(jTextFieldCSP.getText());
            int saldo = 333000;
            sql = "INSERT INTO usuario (nombreUsuario,password,saldo,CSP) ";
            sql += "values ('" + nombreUsuario + "',MD5('" + password + "'),'" + saldo + "','" + CSP + "');";
            try {
                JDBCclass.consulta3(sql);
                JOptionPane.showMessageDialog(null, "¡Creacion del usuario realizada correctamente!");
                main();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "El usuario ya existe");
            }
        }
    }//GEN-LAST:event_BtnCrearUsuarioActionPerformed

    private void BtnBorrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarUsuarioActionPerformed
        // TODO add your handling code here:
        //codigo query para eliminar un usuario seleccionado 
        if (jTable1.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "¡Selecciona un usuario a borrar!");
        } else {
            try {
                JDBCclass JDBC = new JDBCclass();
                String nombreUsuario = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0));
                if (nombreUsuario.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "No se puede eliminar el usuario");
                } else {
                    String sql3 = "SELECT COUNT(nombreCiudad) FROM ciudad WHERE nombreUsuario='" + nombreUsuario + "';";
                    ResultSet rs = JDBC.consulta1(sql3);
                    int temporary = 0;
                    if (rs.next()) {
                        temporary = rs.getInt(1);
                        System.out.println(temporary);
                    }
                    if (temporary != 0) {
                        String sql2;
                        sql2 = "UPDATE ciudad SET precioCiudad=null, nombreUsuario=null, bonificacion=null WHERE nombreUsuario='" + nombreUsuario + "';";
                        JDBC.consulta3(sql2);
                        String sql;
                        sql = "DELETE FROM usuario WHERE nombreUsuario='" + nombreUsuario + "';";
                        JDBC.consulta3(sql);
                        JOptionPane.showMessageDialog(null, "¡Usuario eliminado correctamente!");
                        main();
                    } else {
                        String sql;
                        sql = "DELETE FROM usuario WHERE nombreUsuario='" + nombreUsuario + "';";
                        JDBC.consulta3(sql);
                        JOptionPane.showMessageDialog(null, "¡Usuario eliminado correctamente!");
                        main();
                    }
                }
                JDBC.state.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "No se puede eliminar el usuario");
            }
        }
    }//GEN-LAST:event_BtnBorrarUsuarioActionPerformed

    private void BtnCambiarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCambiarPasswordActionPerformed
        // TODO add your handling code here:
        //codigo query para actualizar la contraseña del usuario
        if (jTable1.getSelectedRow() >= 0) {
            String nombreUsuario = jTextFieldNombre.getText();
            String password = String.valueOf(jPasswordFieldContrasena.getPassword());
            String sql;
            sql = "UPDATE usuario SET password=MD5('" + password + "') WHERE nombreUsuario='" + nombreUsuario + "'; ";
            try {
                JDBCclass.consulta3(sql);
                JOptionPane.showMessageDialog(null, "¡Modificacion realizada correctamente!");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "No se puede modificar el usuario");
            }
        } else {
            JOptionPane.showMessageDialog(null, "¡Selecciona a un usuario!");
        }
    }//GEN-LAST:event_BtnCambiarPasswordActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        LoginScreen logscreen = new LoginScreen();
        logscreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnSalirActionPerformed
    public void insertadatos() {
        if (jTable1.getSelectedRow() >= 0) {
            String usr = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            String pwd = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 1));
            int Csp = (int) (jTable1.getValueAt(jTable1.getSelectedRow(), 2));
            jTextFieldNombre.setText(usr);
            jTextFieldNombre.setEnabled(false);
            jPasswordFieldContrasena.setText(pwd);
            jTextFieldCSP.setText(String.valueOf(Csp));
            jTextFieldCSP.setEnabled(false);
        }else{
        jTextFieldNombre.setEnabled(true);
        jTextFieldCSP.setEnabled(true);
    }
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setCellSelectionEnabled(true);
        insertadatos();
        //aqui un codigo para que se deseleccione una vez acabado de insertar los datos a los jlabel
    }//GEN-LAST:event_jTable1MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        jTable1.setColumnSelectionAllowed(false);
        jTable1.setCellSelectionEnabled(false);
        jTextFieldNombre.setEnabled(true);
        jTextFieldCSP.setEnabled(true);
        jTextFieldNombre.setText(null);
        jPasswordFieldContrasena.setText(null);
        jTextFieldCSP.setText(null);
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main() {
        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            // codigo para añadir a la tabla los usuarios y sus contraseñas
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Nombre");
            modelo.addColumn("Contraseña MD5");
            modelo.addColumn("CSP");
            jTable1.setModel(modelo);
            Object[] usuarios = new Object[3];
            String sql;
            sql = "SELECT * FROM usuario; ";
            JDBCclass JDBC = new JDBCclass();
            ResultSet temporal = JDBC.consulta1(sql);
            while (temporal.next()) {
                String nombreUsuario = temporal.getString("nombreUsuario");
                String contraseña = temporal.getString("password");
                int CSp = temporal.getInt("CSP");
                usuarios[0] = nombreUsuario;
                usuarios[1] = contraseña;
                usuarios[2] = CSp;
                modelo.addRow(usuarios);
            }
            JDBC.state.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Hubo un problema con la visualizacion de las tablas");
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBorrarUsuario;
    private javax.swing.JButton BtnCambiarPassword;
    private javax.swing.JButton BtnCrearUsuario;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordFieldContrasena;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCSP;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
